### ISSUE TITLE
Getting error running "haxelib run kha html5-worker"

### ISSUE THREAD

**Issue by tomde** [KTXSoftware/Kha#240]
/usr/local/lib/haxelib/kha/16,1,2/Tools/khamake/main.js:148
			if (fs.existsSync(pathlib.join(from.toString(), 'Backends'))) {
			                               ^

ReferenceError: from is not defined
    at compileShader (/usr/local/lib/haxelib/kha/16,1,2/Tools/khamake/main.js:148:35)
    at exportKhaProject (/usr/local/lib/haxelib/kha/16,1,2/Tools/khamake/main.js:380:3)
    at exportProject (/usr/local/lib/haxelib/kha/16,1,2/Tools/khamake/main.js:451:3)
    at Object.exports.run.callback [as run] (/usr/local/lib/haxelib/kha/16,1,2/Tools/khamake/main.js:539:2)
    at Object.<anonymous> (/usr/local/lib/haxelib/kha/16,1,2/Tools/khamake/khamake.js:376:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

**Comment by RobDangerous** [comment]
Right, html5-worker is currently not up to date.
Out of interest (and to sort my priorities), do you have anything in mind you'd like to do with it or did you just do some testing?
