### ISSUE TITLE
Kha.Blob not found when compiling to WPF

### ISSUE THREAD

**Issue by RafaelOliveira** [KTXSoftware/Kha#323]
WPF isn't compiling in the latest kha. here is the output:

Creating Kha project.
Exporting asset 1 of 2 (bg.jpg).
Exporting asset 2 of 2 (tree.png).
Assets done.
C:\Dev\SDKs\Kha\Sources/kha/graphics4/Graphics.hx:4: characters 7-15 : Type not found : kha.Blob

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Dev\Projetos\TestBug\build\wpf-build\Project.sln'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at WpfExporter.writeFile (C:\Dev\SDKs\Kha\Tools\khamake\Exporter.js:13:17)
    at WpfExporter.exportSLN (C:\Dev\SDKs\Kha\Tools\khamake\CSharpExporter.js:70:8)
    at WpfExporter.exportSolution (C:\Dev\SDKs\Kha\Tools\khamake\CSharpExporter.js:63:8)
    at exportProjectFiles (C:\Dev\SDKs\Kha\Tools\khamake\main.js:246:42)
    at exportKhaProject (C:\Dev\SDKs\Kha\Tools\khamake\main.js:600:2)
    at exportProject (C:\Dev\SDKs\Kha\Tools\khamake\main.js:609:3)
    at Object.exports.run.callback [as run] (C:\Dev\SDKs\Kha\Tools\khamake\main.js:721:2)
    at Object.<anonymous> (C:\Dev\SDKs\Kha\Tools\khamake\khamake.js:285:23)

**Comment by RobDangerous** [comment]
Can't reproduce this one, kha.Blob exists in the WPF backend. Can you upload a project which doesn't compile?

**Comment by RafaelOliveira** [comment]
https://www.dropbox.com/s/qmk9ythdw88uzxa/TestBug.zip?dl=0

I updated Kha to test again, and now I'm receiving a different error:

Creating Kha project.
Exporting asset 1 of 2 (bg.jpg).
Exporting asset 2 of 2 (tree.png).
Assets done.
C:\Dev\SDKs\Kha\Sources/kha/graphics4/VertexBuffer.hx:3: characters 7-30 : Type not found : kha.arrays.Float32Array

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Dev\Projetos\Kha\BugTests\TestBug\build\wpf-build\Project.sln'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at WpfExporter.writeFile (C:\Dev\SDKs\Kha\Tools\khamake\Exporter.js:13:17)
    at WpfExporter.exportSLN (C:\Dev\SDKs\Kha\Tools\khamake\CSharpExporter.js:70:8)
    at WpfExporter.exportSolution (C:\Dev\SDKs\Kha\Tools\khamake\CSharpExporter.js:63:8)
    at exportProjectFiles (C:\Dev\SDKs\Kha\Tools\khamake\main.js:253:22)
    at exportKhaProject (C:\Dev\SDKs\Kha\Tools\khamake\main.js:610:9)
    at exportProject (C:\Dev\SDKs\Kha\Tools\khamake\main.js:619:10)
    at Object.exports.run.callback [as run] (C:\Dev\SDKs\Kha\Tools\khamake\main.js:732:9)
    at Object.<anonymous> (C:\Dev\SDKs\Kha\Tools\khamake\khamake.js:285:37)

**Comment by RobDangerous** [comment]
Aha, one step further, only happens with non-local Kha...

**Comment by RafaelOliveira** [comment]
Now is working, thanks. Next time I will mention if I'm using a external Kha.
