### ISSUE TITLE
Unable to include libraries in recent versions of Kha

### ISSUE THREAD

**Issue by jamiltron** [KTXSoftware/Kha#361]
Steps to replicate:

1. `git clone --recursive https://github.com/KTXSoftware/Empty.git`
2. Edit Empty/khafile.js  to include the line `project.addLibrary('$ANY_INSTALLED_LIB);` after project declaration, before resolving.
3. `node Kha/make html5` (or any target).

Output:
```
Creating Kha project.
Error: khafile.js did not call resolve, no project created.
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at findLibraryDirectory (/Users/jamiltron/Workspace/Empty/Kha/Tools/khamake/out/Project.js:77:32)
    at Project.addLibrary (/Users/jamiltron/Workspace/Empty/Kha/Tools/khamake/out/Project.js:97:23)
    at eval (eval at <anonymous> (/Users/jamiltron/Workspace/Empty/Kha/Tools/khamake/out/ProjectFile.js:28:17), <anonymous>:6:9)
    at fs.readFile (/Users/jamiltron/Workspace/Empty/Kha/Tools/khamake/out/ProjectFile.js:28:78)
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

This project builds without the addLibrary line.

**Comment by RobDangerous** [comment]
Are you on the very very newest version of Kha (and especially khamake)?

**Comment by RobDangerous** [comment]
Just noticed you're the same guy who asked earlier about ash. If it's still not working please give me more input about your system etc. because it is working for me.

**Comment by jamiltron** [comment]
Yes, I just rechecked out Empty to try again and still have this as an issue.

I am running:
*  OSX 10.11.6
*  Haxe 3.2.1
*  Haxelib 3.2.0-rc.3
*  node 6.2.1

Any other information that's useful?

**Comment by RobDangerous** [comment]
Did you update the copy of Kha inside of Empty?

**Comment by jamiltron** [comment]
D'oh, sorry I forgot to call `git submodule foreach --recursive git pull origin master` .

Sorry for wasting your time!

**Comment by RobDangerous** [comment]
Don't worry about it. Update process is too complicated, have to build something into khamake for that.
