### ISSUE TITLE
Segmentation fault on linux build

### ISSUE THREAD

**Issue by Jumblemuddle** [KTXSoftware/Kha#397]
Cleaned out the build folder and ran `node Kha/make --run`

Here's the backtrace from gdb:

```
(gdb) backtrace 
#0  0x0000000000000000 in ?? ()
#1  0x00000000006d5124 in Kore::Graphics::init(int, int, int) ()
#2  0x00000000006b47e4 in Kore::System::initWindow(Kore::WindowOptions) ()
#3  0x00000000005b57e6 in init_kore_impl(bool, char const*, int, int, int, int, int, Kore::WindowMode, int) ()
#4  0x00000000005b5980 in init_kore(char const*, int, int, int) ()
#5  0x00000000004b15c6 in kha::SystemImpl_obj::init(Dynamic, Dynamic) ()
#6  0x00000000004a9f28 in kha::System_obj::init(Dynamic, Dynamic) ()
#7  0x000000000040885d in Main_obj::main() ()
#8  0x000000000043bb17 in __hxcpp_lib_main ()
#9  0x0000000000693e5b in hxRunLibrary ()
#10 0x00000000005b5a4c in kore(int, char**) ()
#11 0x0000000000417919 in main ()
```

Any ideas?

**Comment by RobDangerous** [comment]
Latest revision didn't compile on my Linux although it did compile in travis. I fixed that but couldn't reproduce the crash. Can you try again with the latest revision?
