### ISSUE TITLE
Error building linux project with latest Kha

### ISSUE THREAD

**Issue by Jumblemuddle** [KTXSoftware/Kha#402]
```
» node Kha/make --run
Creating Kha project.
Exporting asset 1 of 2 (land.png).
Exporting asset 2 of 2 (opensans.ttf).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Compiling code.
ReferenceError: name is not defined
    at createKorefile (/system/dev/tree/Kha/Tools/khamake/out/main.js:48:44)
    at /system/dev/tree/Kha/Tools/khamake/out/main.js:102:70
    at next (native)
    at fulfilled (/system/dev/tree/Kha/Tools/khamake/out/main.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Jumblemuddle** [comment]
Thanks, @RobDangerous !

**Comment by RobDangerous** [comment]
Glad to help.
