### ISSUE TITLE
Error on android

### ISSUE THREAD

**Issue by RafaelOliveira** [KTXSoftware/Kha#67]
I'm trying to execute the Empty example on android, but is crashing with this error in logcat:

```
06-08 18:36:42.725: W/dalvikvm(24895): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/ktxsoftware/kore/KoreLib;
06-08 18:36:42.725: W/dalvikvm(24895): threadid=11: thread exiting with uncaught exception (group=0x4169cd40)
06-08 18:36:42.727: E/AndroidRuntime(24895): FATAL EXCEPTION: GLThread 78018
06-08 18:36:42.727: E/AndroidRuntime(24895): Process: com.ktxsoftware.kore, PID: 24895
06-08 18:36:42.727: E/AndroidRuntime(24895): java.lang.UnsatisfiedLinkError: Couldn't load Kore from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ktxsoftware.kore-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.ktxsoftware.kore-2, /vendor/lib, /system/lib]]]: findLibrary returned null
06-08 18:36:42.727: E/AndroidRuntime(24895): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
06-08 18:36:42.727: E/AndroidRuntime(24895): 	at java.lang.System.loadLibrary(System.java:526)
06-08 18:36:42.727: E/AndroidRuntime(24895): 	at com.ktxsoftware.kore.KoreLib.<clinit>(KoreLib.java:7)
06-08 18:36:42.727: E/AndroidRuntime(24895): 	at com.ktxsoftware.kore.KoreActivity$1.run(KoreActivity.java:140)
06-08 18:36:42.727: E/AndroidRuntime(24895): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1463)
06-08 18:36:42.727: E/AndroidRuntime(24895): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

I'm new to Kha, and new to the use of submodules in git, I found this command to update all the submodules:
git submodule foreach --recursive git pull origin master
all the submodules were pulled

**Comment by RafaelOliveira** [comment]
The problem was that NDK wasn't configured.
